name: run-tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-22.04

        strategy:
            fail-fast: true
            matrix:
                php: [ 8.1, 8.2, 8.3 ]
                laravel: [ 10, 11 ]
                exclude:
                    -   php: 8.1
                        laravel: 11

        name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  ini-values: error_reporting=E_ALL
                  tools: composer:v2
                  coverage: none

            - name: Setup problem matchers
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:^${{ matrix.laravel }}" --no-update
                  composer update --prefer-dist --no-interaction --no-progress

            - name: Execute tests
              timeout-minutes: 2
              run: vendor/bin/pest
